[functions.invite-user]
verify_jwt = false

[functions.change-user-email]
verify_jwt = false

[functions.trial-voucher-public]
verify_jwt = false

[functions.trial-voucher-admin]
verify_jwt = false

[functions.send-trial-voucher-email]
verify_jwt = false

[functions.create-trial-voucher-checkout]
verify_jwt = false

[functions.trial-voucher-stripe-webhook]
verify_jwt = false

[functions.xero-connect]
verify_jwt = false
