/*
  Rewrite the CASA RPL(A) course and lesson narrative fields in plain English.
  Formal assessment detail remains in the syllabus matrix tables.
*/

UPDATE public.training_courses
SET
  description = 'A practical CASA RPL(A) training course for students working toward the Recreational Pilot Licence aeroplane category rating. The course starts with core aircraft handling, then builds through circuits, emergencies, solo consolidation, training area work, basic instrument flying and final flight test preparation.',
  objectives = ARRAY[
    'Build safe aircraft handling from basic effects of controls through to flight test standard.',
    'Teach students to plan, fly, communicate and make sound decisions as a pilot in command.',
    'Record progress clearly against the CASA RPL syllabus matrix without overwhelming the lesson notes.',
    'Prepare the student for solo flight, training area operations, required exams and the final RPL flight test.'
  ]::text[],
  evaluation_criteria = ARRAY[
    'Can the student safely prepare, fly and secure the aircraft for this lesson?',
    'Can the student explain what they are doing in plain language and make safe decisions?',
    'Has the student met the required CASA matrix items for this lesson?',
    'If something was not yet met, is it clearly carried forward for the next lesson?'
  ]::text[]
WHERE title = 'CASA RPL(A) v1.2';

WITH lesson_updates(sequence_code, objective, flight_exercises, theory) AS (
  VALUES
  ('RPL(A)1',
   'Introduce how the aircraft responds to each control and build safe habits before, during and after the flight.',
   '<p><strong>Lesson overview</strong></p><p>The student learns what each control does and how the aircraft reacts on the ground and in the air.</p><p><strong>Flight exercises</strong></p><ul><li>Complete pre-flight paperwork and aircraft checks.</li><li>Start, taxi and position the aircraft safely.</li><li>Demonstrate primary and secondary effects of controls.</li><li>Use trim, power, flap and balance correctly.</li><li>Maintain lookout and traffic separation.</li><li>Shut down, secure the aircraft and complete post-flight paperwork.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>How elevator, aileron, rudder, trim, power and flap affect the aircraft.</li><li>Why lookout, checklist discipline and smooth control inputs matter from the first lesson.</li></ul>'),
  ('RPL(A)2',
   'Teach the student to hold straight and level flight accurately at different speeds and configurations.',
   '<p><strong>Lesson overview</strong></p><p>The student practises keeping the aircraft straight, level, balanced and trimmed.</p><p><strong>Flight exercises</strong></p><ul><li>Maintain heading and altitude using outside references and instruments.</li><li>Fly straight and level at normal, slow and faster cruise speeds.</li><li>Use power, attitude, trim and configuration to achieve the desired performance.</li><li>Keep the aircraft balanced and maintain effective lookout.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Relationship between attitude, power, trim and performance.</li><li>Altimeter setting, lookout, balance and basic flight tolerances.</li></ul>'),
  ('RPL(A)3',
   'Teach safe climbs and descents, including how to enter, maintain and level off accurately.',
   '<p><strong>Lesson overview</strong></p><p>The student learns how to climb and descend using the right attitude, power and configuration.</p><p><strong>Flight exercises</strong></p><ul><li>Enter and maintain cruise, best-rate and best-angle climbs.</li><li>Enter and maintain powered, glide and approach descents.</li><li>Level off smoothly at nominated altitudes.</li><li>Manage fuel, engine, trim, lookout and radio workload during altitude changes.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Vy, Vx, glide, approach descents and level-off technique.</li><li>Fuel checks, altimetry, traffic awareness and workload management.</li></ul>'),
  ('RPL(A)4',
   'Develop coordinated turning, including medium turns, climbing turns and descending turns.',
   '<p><strong>Lesson overview</strong></p><p>The student learns to turn accurately while keeping the aircraft balanced and under control.</p><p><strong>Flight exercises</strong></p><ul><li>Demonstrate adverse yaw and coordinated use of aileron and rudder.</li><li>Practise medium level turns, climbing turns and descending turns.</li><li>Roll in and out smoothly on selected headings.</li><li>Recognise poor balance, overbanking and early signs of spiral dive.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Lift, drag, balance and overbanking tendency in turns.</li><li>Situational awareness, lookout before turning and safe correction of handling errors.</li></ul>'),
  ('RPL(A)5',
   'Teach slow flight and basic stall recognition, prevention and recovery.',
   '<p><strong>Lesson overview</strong></p><p>The student learns how the aircraft behaves near the stall and how to recover safely.</p><p><strong>Flight exercises</strong></p><ul><li>Practise slow flight while maintaining height, heading and balance.</li><li>Recognise stall symptoms and warning signs.</li><li>Recover promptly using the correct actions.</li><li>Discuss how stalls can happen in real operations.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Angle of attack, stall speed, configuration and load factor.</li><li>Stall prevention, recovery priorities and human factors around startle response.</li></ul>'),
  ('RPL(A)6',
   'Introduce the circuit pattern and the normal take-off, approach and landing sequence.',
   '<p><strong>Lesson overview</strong></p><p>The student starts building the pattern, checks and judgement needed for circuit flying.</p><p><strong>Flight exercises</strong></p><ul><li>Fly the upwind, crosswind, downwind, base and final legs.</li><li>Practise take-off, climb-out, approach set-up and landing attitude.</li><li>Use downwind checks, radio calls and spacing.</li><li>Introduce go-around decision making.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Circuit layout, radio calls, runway direction, spacing and approach path judgement.</li><li>Threats in the circuit and when to go around.</li></ul>'),
  ('RPL(A)7',
   'Build consistent normal circuits, landings and go-arounds.',
   '<p><strong>Lesson overview</strong></p><p>The student repeats circuits to improve accuracy, timing and decision making.</p><p><strong>Flight exercises</strong></p><ul><li>Practise normal take-offs, approaches and landings.</li><li>Maintain circuit spacing and stable approach criteria.</li><li>Carry out go-arounds from different stages of the approach.</li><li>Improve radio calls, checks and lookout.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Stabilised approach, flare, landing attitude and go-around actions.</li><li>Common landing errors and safe correction strategies.</li></ul>'),
  ('RPL(A)8',
   'Teach flapless approaches and missed approaches so the student can manage abnormal circuit situations.',
   '<p><strong>Lesson overview</strong></p><p>The student practises circuits when the approach is not normal or a landing should not continue.</p><p><strong>Flight exercises</strong></p><ul><li>Fly flapless approaches and compare the changed picture.</li><li>Practise missed approaches and go-arounds.</li><li>Manage spacing, speed and runway aim point.</li><li>Keep radio calls and workload organised.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>How flap affects approach speed, descent angle and landing distance.</li><li>Go-around triggers, missed approach actions and workload traps.</li></ul>'),
  ('RPL(A)9',
   'Teach safe responses to common circuit emergencies.',
   '<p><strong>Lesson overview</strong></p><p>The student learns how to handle emergencies close to the aerodrome.</p><p><strong>Flight exercises</strong></p><ul><li>Practise engine failure after take-off decision making.</li><li>Practise abnormal approaches and urgent go-arounds.</li><li>Manage radio calls, passenger brief and aircraft control.</li><li>Keep priorities clear: aviate, navigate, communicate.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>EFATO options, turn-back risk, emergency checks and forced landing priorities.</li><li>Human factors in sudden emergencies.</li></ul>'),
  ('RPL(A)10',
   'Check that the student is ready for first solo circuits.',
   '<p><strong>Lesson overview</strong></p><p>This is a final dual check before authorising the first solo circuit.</p><p><strong>Flight exercises</strong></p><ul><li>Confirm safe normal circuits, landings and go-arounds.</li><li>Check emergency handling and decision making.</li><li>Confirm radio calls, checks, lookout and circuit spacing.</li><li>Identify anything that must be repeated before solo.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Solo limitations, local procedures, weather limits and instructor authorisation.</li><li>Presolo exam and required briefings should be complete before solo release.</li></ul>'),
  ('RPL(A)11',
   'Complete the student''s first solo circuit under instructor supervision.',
   '<p><strong>Lesson overview</strong></p><p>The student completes a short solo circuit exercise after instructor approval.</p><p><strong>Flight exercises</strong></p><ul><li>Confirm conditions and limitations before release.</li><li>Fly the authorised solo circuit profile.</li><li>Debrief immediately after landing.</li><li>Record any points to consolidate next lesson.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Solo responsibilities, weather awareness, radio discipline and personal minimums.</li></ul>'),
  ('RPL(A)12',
   'Consolidate circuit skills after first solo and confirm readiness for further solo circuits.',
   '<p><strong>Lesson overview</strong></p><p>The student improves consistency after first solo and addresses any weak areas.</p><p><strong>Flight exercises</strong></p><ul><li>Review normal circuits, landings and go-arounds.</li><li>Practise any approach or landing items needing improvement.</li><li>Confirm emergency handling remains sound.</li><li>Decide whether further solo circuits are suitable.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Post-solo risk management, fatigue, weather changes and circuit judgement.</li></ul>'),
  ('RPL(A)13',
   'Build confidence and consistency through supervised solo circuit practice.',
   '<p><strong>Lesson overview</strong></p><p>The student practises authorised solo circuits to strengthen consistency.</p><p><strong>Flight exercises</strong></p><ul><li>Fly solo circuits within instructor-set limits.</li><li>Maintain spacing, checks, radio calls and stable approaches.</li><li>Record any unusual events or learning points after the flight.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Self-assessment, personal limits and how to decide when to discontinue solo practice.</li></ul>'),
  ('RPL(A)14',
   'Continue circuit consolidation and correct any remaining landing or judgement issues.',
   '<p><strong>Lesson overview</strong></p><p>The student works toward reliable circuit performance in normal conditions.</p><p><strong>Flight exercises</strong></p><ul><li>Refine take-off, circuit tracking, approach and landing accuracy.</li><li>Practise go-arounds and abnormal circuit situations as required.</li><li>Confirm readiness for further solo practice.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Landing judgement, wind correction, approach stability and instructor-set solo limits.</li></ul>'),
  ('RPL(A)15',
   'Continue supervised solo circuits to build reliability and judgement.',
   '<p><strong>Lesson overview</strong></p><p>The student completes more solo circuit practice under supervision.</p><p><strong>Flight exercises</strong></p><ul><li>Fly solo circuits within the authorised envelope.</li><li>Maintain consistent approaches and landings.</li><li>Debrief any errors or unstable approaches honestly.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Monitoring weather, aircraft performance and personal workload while solo.</li></ul>'),
  ('RPL(A)16',
   'Develop advanced stall awareness and scenario-based recovery.',
   '<p><strong>Lesson overview</strong></p><p>The student practises stall recognition and recovery in more realistic situations.</p><p><strong>Flight exercises</strong></p><ul><li>Review basic stall recovery.</li><li>Practise stalls or near-stall scenarios linked to turns, approach and configuration changes.</li><li>Recover while maintaining safe priorities and situational awareness.</li><li>Discuss prevention before recovery.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Stall risk in the circuit, distraction, configuration and load factor.</li><li>Decision making and recovery priorities under pressure.</li></ul>'),
  ('RPL(A)17',
   'Teach forced landing planning and execution after simulated engine failure.',
   '<p><strong>Lesson overview</strong></p><p>The student learns how to choose a landing area and manage a forced landing pattern.</p><p><strong>Flight exercises</strong></p><ul><li>Practise engine failure checks and restart attempts.</li><li>Select a suitable landing area.</li><li>Fly a safe forced landing pattern.</li><li>Use radio calls, passenger brief and shutdown actions at the right time.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Forced landing priorities, field selection, glide management and emergency communication.</li></ul>'),
  ('RPL(A)18',
   'Teach steep turns and improve aircraft handling at higher workload.',
   '<p><strong>Lesson overview</strong></p><p>The student practises steeper turns while keeping control, lookout and orientation.</p><p><strong>Flight exercises</strong></p><ul><li>Enter, maintain and recover from steep turns.</li><li>Maintain height, speed, balance and lookout.</li><li>Recognise and correct overbanking or excessive nose drop.</li><li>Manage disorientation and workload.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Load factor, stall speed increase, overbanking and energy management.</li></ul>'),
  ('RPL(A)19',
   'Develop crosswind circuit, approach and landing judgement.',
   '<p><strong>Lesson overview</strong></p><p>The student practises circuit operations when wind affects tracking and landing.</p><p><strong>Flight exercises</strong></p><ul><li>Apply drift correction around the circuit.</li><li>Practise crosswind approaches and landings.</li><li>Use suitable crosswind technique for the aircraft.</li><li>Decide when conditions exceed limits.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Crosswind limits, drift correction, crab, sideslip and go-around decision making.</li></ul>'),
  ('RPL(A)20',
   'Check that the student is ready for first solo in the training area.',
   '<p><strong>Lesson overview</strong></p><p>This is a final dual check before authorising solo training area operations.</p><p><strong>Flight exercises</strong></p><ul><li>Confirm departure, area navigation and return procedures.</li><li>Check general handling, emergency response and radio calls.</li><li>Confirm boundaries, altitude limits and weather suitability.</li><li>Identify any items to repeat before release.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Training area boundaries, airspace, radio procedures, lost procedure and solo limitations.</li></ul>'),
  ('RPL(A)21',
   'Complete the first authorised solo training area flight.',
   '<p><strong>Lesson overview</strong></p><p>The student conducts a supervised solo flight in the training area within strict limits.</p><p><strong>Flight exercises</strong></p><ul><li>Depart, operate in the training area and return as briefed.</li><li>Maintain navigation awareness, lookout and radio calls.</li><li>Stop or return early if conditions or workload require it.</li><li>Debrief the flight in detail after landing.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Solo area decision making, weather monitoring and personal minimums.</li></ul>'),
  ('RPL(A)22',
   'Teach short-field take-off and landing technique.',
   '<p><strong>Lesson overview</strong></p><p>The student learns how to operate safely when runway length or surface is more limiting.</p><p><strong>Flight exercises</strong></p><ul><li>Plan and brief short-field performance.</li><li>Practise short-field take-offs and approaches.</li><li>Control speed, aim point and touchdown accuracy.</li><li>Use go-around when the approach is not suitable.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Performance charts, runway surface, obstacle clearance and short-field risk management.</li></ul>'),
  ('RPL(A)23',
   'Consolidate general handling, circuit, emergency and decision-making skills.',
   '<p><strong>Lesson overview</strong></p><p>The student revises key skills and fills any gaps before moving deeper into licence preparation.</p><p><strong>Flight exercises</strong></p><ul><li>Practise selected handling exercises needing improvement.</li><li>Review circuits, emergencies and abnormal situations as required.</li><li>Strengthen radio, lookout and workload management.</li><li>Carry forward any weak items clearly.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Review knowledge gaps, exam preparation and practical decision making.</li></ul>'),
  ('RPL(A)24',
   'Teach precautionary search and landing technique.',
   '<p><strong>Lesson overview</strong></p><p>The student learns how to inspect and assess a possible landing area before committing.</p><p><strong>Flight exercises</strong></p><ul><li>Assess weather, terrain and landing area suitability.</li><li>Fly inspection passes at safe heights.</li><li>Plan approach, overshoot and passenger briefing.</li><li>Practise decision making for precautionary landing scenarios.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Precautionary landing triggers, inspection pattern, hazards and passenger management.</li></ul>'),
  ('RPL(A)25',
   'Build solo confidence and judgement through additional authorised solo practice.',
   '<p><strong>Lesson overview</strong></p><p>The student completes solo consolidation under instructor supervision and limits.</p><p><strong>Flight exercises</strong></p><ul><li>Fly authorised solo tasks in the circuit or training area.</li><li>Practise self-management, navigation awareness and safe return.</li><li>Debrief decisions, handling and any uncertainty after landing.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Solo risk management, weather judgement and when to seek instructor guidance.</li></ul>'),
  ('RPL(A)26',
   'Introduce basic instrument flying for safe control if outside references are reduced.',
   '<p><strong>Lesson overview</strong></p><p>The student learns to control the aircraft by reference to instruments for limited basic scenarios.</p><p><strong>Flight exercises</strong></p><ul><li>Maintain straight and level, climbs, descents and turns using instruments.</li><li>Recover from unusual attitudes using a safe scan.</li><li>Manage workload and avoid over-controlling.</li><li>Discuss why VFR pilots must avoid IMC.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Instrument scan, spatial disorientation, VFR into IMC risk and recovery priorities.</li></ul>'),
  ('RPL(A)27',
   'Consolidate the full RPL skill set and confirm exam/theory progress.',
   '<p><strong>Lesson overview</strong></p><p>The student reviews any remaining weak areas and prepares for final licence standard.</p><p><strong>Flight exercises</strong></p><ul><li>Revise selected general handling, circuits, emergencies and navigation items.</li><li>Check that carried-forward matrix items are being closed.</li><li>Confirm required exams and KDR follow-up are progressing.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>RPL aeronautical knowledge exam, radio exam, aviation English and KDR review where required.</li></ul>'),
  ('RPL(A)28',
   'Continue consolidation until the student can consistently perform at RPL standard.',
   '<p><strong>Lesson overview</strong></p><p>The student practises remaining weak items and builds consistency before pre-licence checks.</p><p><strong>Flight exercises</strong></p><ul><li>Target any outstanding matrix items.</li><li>Practise realistic flight scenarios and abnormal events.</li><li>Confirm safe command decisions and workload management.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Review limitations, local procedures, flight planning and decision making.</li></ul>'),
  ('RPL(A)29',
   'Complete further solo consolidation if authorised and suitable.',
   '<p><strong>Lesson overview</strong></p><p>The student uses solo practice to polish consistency before final licence preparation.</p><p><strong>Flight exercises</strong></p><ul><li>Complete authorised solo tasks only within set limits.</li><li>Maintain safe radio, navigation, lookout and return procedures.</li><li>Debrief any handling, navigation or judgement issues.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Self-checking, personal minimums and recognising when not to continue a solo task.</li></ul>'),
  ('RPL(A)30',
   'Complete final pre-licence preparation and decide whether the student is ready for the RPL flight test.',
   '<p><strong>Lesson overview</strong></p><p>This lesson checks the student''s readiness for the final flight test.</p><p><strong>Flight exercises</strong></p><ul><li>Run a practical review across the expected flight test profile.</li><li>Confirm all required matrix items, exams and documents are complete.</li><li>Review any remaining weak areas and decide whether to recommend for test.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Flight test expectations, licence privileges, limitations, documents and oral questions.</li></ul>'),
  ('RPL(A)FT',
   'Complete the RPL(A) flight test and record the final outcome.',
   '<p><strong>Lesson overview</strong></p><p>The student completes the final flight test for the RPL(A) aeroplane category rating.</p><p><strong>Flight exercises</strong></p><ul><li>Assess pre-flight planning, aircraft handling, circuits, emergencies and decision making.</li><li>Confirm the student can operate safely as pilot in command within RPL privileges.</li><li>Record the result, limitations, follow-up actions and endorsement outcome.</li></ul>',
   '<p><strong>Theory focus</strong></p><ul><li>Confirm required exams, KDRs, aviation English, student records and final paperwork are complete.</li></ul>')
)
UPDATE public.training_lessons lesson
SET
  objective = lesson_updates.objective,
  flight_exercises = lesson_updates.flight_exercises,
  theory = lesson_updates.theory,
  student_preparation = regexp_replace(lesson_updates.theory, '<[^>]+>', ' ', 'g'),
  instructor_notes = regexp_replace(lesson_updates.flight_exercises, '<[^>]+>', ' ', 'g')
FROM lesson_updates
JOIN public.training_courses course ON course.title = 'CASA RPL(A) v1.2'
WHERE course.id = lesson.course_id
  AND lesson.sequence_code = lesson_updates.sequence_code;
