-- Complete, production-derived function permission manifest and first grant-reduction batch.
-- The matching readable manifest is config/database-function-permissions.json.
create schema if not exists private;
revoke all on schema private from public,anon,authenticated;

create table if not exists private.function_permission_manifest(
 signature text primary key,
 function_name text not null,
 classification text not null check(classification in('anonymous_token_public','authenticated_self_service','staff_aal2','service_worker','trigger_internal')),
 allowed_roles text[] not null,
 security_definer boolean not null,
 fixed_search_path boolean not null,
 rationale text not null,
 reviewed_at date not null default date '2026-08-03'
);
truncate private.function_permission_manifest;
insert into private.function_permission_manifest(signature,function_name,classification,allowed_roles,security_definer,fixed_search_path,rationale) values
  ('public.account_is_linked_to_xero(target_user_id uuid)','account_is_linked_to_xero','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.acknowledge_booking_supervision(p_booking_id uuid)','acknowledge_booking_supervision','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.acknowledge_training_record_with_token(p_token text, p_user_agent text)','acknowledge_training_record_with_token','anonymous_token_public',ARRAY['anon','authenticated','service_role']::text[],true,true,'Login-free workflow protected by an expiring, scoped token.'),
  ('public.admin_audit_trigger()','admin_audit_trigger','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.apply_booking_conflict_policy()','apply_booking_conflict_policy','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.apply_flight_review_completion()','apply_flight_review_completion','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.apply_ground_session_rate_matrix()','apply_ground_session_rate_matrix','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.apply_membership_scholarship_contribution()','apply_membership_scholarship_contribution','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.archive_organisation_document(p_document_id uuid)','archive_organisation_document','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.archive_trial_voucher_account_after_logged_flight()','archive_trial_voucher_account_after_logged_flight','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.assert_current_membership_documents_acknowledged(p_document_ids uuid[])','assert_current_membership_documents_acknowledged','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.assert_learning_step_access(p_step_id uuid, p_require_previous boolean)','assert_learning_step_access','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.assess_instructor_duty_booking(p_instructor_id uuid, p_start timestamp with time zone, p_end timestamp with time zone, p_exclude_booking_id uuid)','assess_instructor_duty_booking','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.assess_member_booking_eligibility(p_user_id uuid, p_booking_start timestamp with time zone, p_is_guest boolean, p_has_aircraft boolean)','assess_member_booking_eligibility','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.audit_and_reconcile_maintenance_milestone()','audit_and_reconcile_maintenance_milestone','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.audit_changed_fields(old_row jsonb, new_row jsonb)','audit_changed_fields','service_worker',ARRAY['service_role']::text[],false,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.audit_defect_change()','audit_defect_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.audit_flight_review_record_change()','audit_flight_review_record_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.audit_instructor_compliance_record()','audit_instructor_compliance_record','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.audit_operations_row()','audit_operations_row','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.audit_record_label(table_name text, row_data jsonb)','audit_record_label','service_worker',ARRAY['service_role']::text[],false,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.audit_xero_configuration_change()','audit_xero_configuration_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.audit_xero_connection_change()','audit_xero_connection_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.authorize_membership_fee_waiver(p_period_id uuid, p_waiver_type text, p_reason text, p_authority_reference text)','authorize_membership_fee_waiver','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.bind_new_xero_reference_to_tenant()','bind_new_xero_reference_to_tenant','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.bind_xero_queue_tenant()','bind_xero_queue_tenant','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.book_trial_flight_voucher_slot(p_voucher_id uuid, p_student_id uuid, p_aircraft_id uuid, p_instructor_id uuid, p_start_time timestamp with time zone, p_end_time timestamp with time zone, p_notes text)','book_trial_flight_voucher_slot','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.casa_appendix_6_fdp_limit_hours(p_start timestamp with time zone)','casa_appendix_6_fdp_limit_hours','authenticated_self_service',ARRAY['authenticated','service_role']::text[],false,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.claim_integration_webhook_deliveries(p_limit integer, p_lease_timeout_seconds integer)','claim_integration_webhook_deliveries','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.claim_xero_api_slot(max_calls_per_minute integer, max_calls_per_day integer, spacing_ms integer)','claim_xero_api_slot','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.claim_xero_token_refresh(p_lock_id uuid, p_lease_seconds integer)','claim_xero_token_refresh','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.commence_membership_application_internal(p_application_id uuid, p_method text, p_actor_id uuid)','commence_membership_application_internal','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.complete_learning_step(p_step_id uuid)','complete_learning_step','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.complete_maintenance_milestone(p_milestone_id uuid, p_completed_date date, p_completed_tach numeric, p_next_due_hours numeric, p_next_due_date date, p_notes text, p_operation_id uuid)','complete_maintenance_milestone','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.create_integration_api_key(p_name text, p_scopes text[], p_expires_at timestamp with time zone)','create_integration_api_key','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.create_integration_webhook(p_name text, p_url text, p_events text[])','create_integration_webhook','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.create_membership_application_for_new_user()','create_membership_application_for_new_user','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.create_membership_payment_preference_for_new_user()','create_membership_payment_preference_for_new_user','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.current_user_has_full_portal_access()','current_user_has_full_portal_access','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.current_user_has_staff_role()','current_user_has_staff_role','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.current_user_is_admin()','current_user_is_admin','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.current_user_is_cfi()','current_user_is_cfi','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.current_user_is_staff()','current_user_is_staff','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.decide_membership_application(p_application_id uuid, p_decision text, p_reason text)','decide_membership_application','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.delete_training_record_draft(p_record_id uuid)','delete_training_record_draft','staff_aal2',ARRAY['authenticated','service_role']::text[],false,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.disable_kiosk_access_internal(p_actor_user_id uuid)','disable_kiosk_access_internal','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.duty_geo_distance_metres(p_latitude_a double precision, p_longitude_a double precision, p_latitude_b double precision, p_longitude_b double precision)','duty_geo_distance_metres','authenticated_self_service',ARRAY['authenticated','service_role']::text[],false,false,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.effective_daily_duty_limit_hours(p_start timestamp with time zone)','effective_daily_duty_limit_hours','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.enforce_aircraft_maintenance_serviceability()','enforce_aircraft_maintenance_serviceability','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.enforce_aircraft_solo_hire_qualifications()','enforce_aircraft_solo_hire_qualifications','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.enforce_booking_membership_eligibility()','enforce_booking_membership_eligibility','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.enforce_cfi_instructor_dependency()','enforce_cfi_instructor_dependency','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.enforce_member_active_booking_limit()','enforce_member_active_booking_limit','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.enqueue_integration_event()','enqueue_integration_event','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.find_available_supervisor(p_trainee_instructor_id uuid, p_start timestamp with time zone, p_end timestamp with time zone, p_location text, p_activity_type text, p_exclude_booking_id uuid)','find_available_supervisor','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.find_next_available_slots(p_after timestamp with time zone, p_duration_minutes integer, p_search_days integer, p_aircraft_ids uuid[], p_instructor_ids uuid[], p_location_id uuid, p_limit integer)','find_next_available_slots','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.get_declaration_signing_request(p_token text)','get_declaration_signing_request','anonymous_token_public',ARRAY['anon','authenticated','service_role']::text[],true,true,'Login-free workflow protected by an expiring, scoped token.'),
  ('public.get_logged_instructor_flight_summary(p_instructor_id uuid, p_duty_date date)','get_logged_instructor_flight_summary','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.get_public_membership_configuration()','get_public_membership_configuration','anonymous_token_public',ARRAY['anon','authenticated','service_role']::text[],true,true,'Minimal public membership configuration used before sign-in.'),
  ('public.get_training_record_acknowledgement(p_token text)','get_training_record_acknowledgement','anonymous_token_public',ARRAY['anon','authenticated','service_role']::text[],true,true,'Login-free workflow protected by an expiring, scoped token.'),
  ('public.guard_and_audit_training_record_update()','guard_and_audit_training_record_update','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.guard_students_self_service_update()','guard_students_self_service_update','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.guard_users_self_service_update()','guard_users_self_service_update','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.handle_aircraft_grounding()','handle_aircraft_grounding','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.handle_endorsement_flight_review_sync()','handle_endorsement_flight_review_sync','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.handle_endorsement_role_sync()','handle_endorsement_role_sync','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.handle_licence_role_sync()','handle_licence_role_sync','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.handle_maintenance_settings_reconciliation()','handle_maintenance_settings_reconciliation','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.handle_new_user()','handle_new_user','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.import_legacy_membership(p_user_id uuid, p_membership_class_code text, p_commenced_at date, p_fee_disposition text, p_reason text)','import_legacy_membership','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.instructor_available_at_location_for_slot(p_instructor_id uuid, p_start_time timestamp with time zone, p_end_time timestamp with time zone, p_location_id uuid)','instructor_available_at_location_for_slot','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.instructor_requires_role_supervision(p_instructor_id uuid)','instructor_requires_role_supervision','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.instructor_roster_location_for_slot(p_instructor_id uuid, p_start_time timestamp with time zone, p_end_time timestamp with time zone)','instructor_roster_location_for_slot','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.lease_next_xero_sync_job(p_worker_id text, p_lease_seconds integer)','lease_next_xero_sync_job','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.link_membership_xero_invoice(p_period_id uuid, p_invoice_id text, p_invoice_number text, p_invoice_status text, p_amount_due numeric)','link_membership_xero_invoice','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.list_calendar_instructors()','list_calendar_instructors','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.maximum_duty_end(p_start timestamp with time zone)','maximum_duty_end','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.membership_financial_year_bounds(p_date date)','membership_financial_year_bounds','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.membership_is_linked_to_xero(target_membership_id uuid)','membership_is_linked_to_xero','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.membership_period_amount(p_class_id uuid, p_commencement_date date)','membership_period_amount','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.mobile_end_break(p_ended_at timestamp with time zone)','mobile_end_break','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.mobile_end_duty(p_actual_end timestamp with time zone, p_flight_minutes integer, p_notes text, p_device_platform text, p_break_taken boolean, p_break_start timestamp with time zone, p_break_end timestamp with time zone)','mobile_end_duty','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.mobile_get_duty_context()','mobile_get_duty_context','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.mobile_start_break(p_started_at timestamp with time zone)','mobile_start_break','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.mobile_start_duty(p_actual_start timestamp with time zone, p_location_label text, p_latitude double precision, p_longitude double precision, p_accuracy_metres numeric, p_duty_clock_location_id uuid, p_geofence_notes text, p_fit_for_duty boolean, p_external_duty_declared boolean, p_sleep_opportunity_confirmed boolean, p_kss_score integer, p_private_note text, p_device_platform text)','mobile_start_duty','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.mobile_user_can_clock_duty(p_user_id uuid)','mobile_user_can_clock_duty','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.note_xero_rate_limit(retry_after_seconds integer)','note_xero_rate_limit','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.notify_booking_cancellation_fee()','notify_booking_cancellation_fee','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.notify_instructor_booking_request(booking_id uuid)','notify_instructor_booking_request','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.notify_instructor_compliance_result()','notify_instructor_compliance_result','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.notify_staff_of_licence_submission()','notify_staff_of_licence_submission','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prepare_booking_duty_and_supervision()','prepare_booking_duty_and_supervision','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prepare_defect_write()','prepare_defect_write','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prepare_instructor_compliance_record()','prepare_instructor_compliance_record','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prepare_maintenance_milestone()','prepare_maintenance_milestone','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prepare_maintenance_settings()','prepare_maintenance_settings','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prepare_maintenance_template()','prepare_maintenance_template','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prepare_membership_renewals(p_as_of date)','prepare_membership_renewals','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.prevent_approved_xero_mapping_change()','prevent_approved_xero_mapping_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prevent_expected_xero_tenant_change()','prevent_expected_xero_tenant_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prevent_self_service_access_field_changes()','prevent_self_service_access_field_changes','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prevent_trial_voucher_booking_overlap()','prevent_trial_voucher_booking_overlap','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prevent_uncovered_supervised_flight_log()','prevent_uncovered_supervised_flight_log','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.prevent_xero_tenant_rebind()','prevent_xero_tenant_rebind','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.process_membership_lifecycle(p_as_of timestamp with time zone)','process_membership_lifecycle','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.process_student_course_record_import(p_student_id uuid, p_course_id uuid, p_course_version text, p_record_type text, p_filename text, p_rows jsonb, p_commit boolean, p_request_student_acknowledgement boolean)','process_student_course_record_import','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.process_student_course_record_import_core(p_student_id uuid, p_course_id uuid, p_course_version text, p_record_type text, p_filename text, p_rows jsonb, p_commit boolean, p_request_student_acknowledgement boolean)','process_student_course_record_import_core','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.process_student_record_import(p_student_id uuid, p_record_type text, p_filename text, p_rows jsonb, p_commit boolean, p_request_student_acknowledgement boolean)','process_student_record_import','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.process_student_review_record_import(p_student_id uuid, p_course_id uuid, p_course_version text, p_filename text, p_rows jsonb, p_commit boolean)','process_student_review_record_import','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.promote_pilot_after_passed_flight_review()','promote_pilot_after_passed_flight_review','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.protect_and_sync_organisation_location()','protect_and_sync_organisation_location','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.protect_candidate_flight_review_update()','protect_candidate_flight_review_update','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.protect_flight_review_import_provenance()','protect_flight_review_import_provenance','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.protect_role_mandated_supervision_requirement()','protect_role_mandated_supervision_requirement','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.protect_student_matrix_import_provenance()','protect_student_matrix_import_provenance','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.protect_student_record_import_provenance()','protect_student_record_import_provenance','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.protect_system_payment_methods()','protect_system_payment_methods','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.publish_organisation_document_version(p_replaces_document_id uuid, p_code text, p_title text, p_version text, p_effective_date date, p_storage_path text, p_uploaded_file_name text, p_file_size_bytes bigint, p_mime_type text, p_acknowledgement_required boolean, p_notes text)','publish_organisation_document_version','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.queue_xero_contact_sync_on_user_change()','queue_xero_contact_sync_on_user_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.queue_xero_flight_invoice_sync()','queue_xero_flight_invoice_sync','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.queue_xero_verified_payment_sync()','queue_xero_verified_payment_sync','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.queue_xero_voucher_sync_from_flight_log()','queue_xero_voucher_sync_from_flight_log','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.queue_xero_voucher_sync_from_voucher()','queue_xero_voucher_sync_from_voucher','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.reconcile_aircraft_maintenance_status(p_aircraft_id uuid, p_cause text)','reconcile_aircraft_maintenance_status','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.reconcile_automatic_duty_periods(p_now timestamp with time zone)','reconcile_automatic_duty_periods','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.reconcile_flight_review_endorsements()','reconcile_flight_review_endorsements','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.reconcile_role_based_supervision_requirements()','reconcile_role_based_supervision_requirements','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.record_booking_duty_and_supervision()','record_booking_duty_and_supervision','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.record_membership_booking_override()','record_membership_booking_override','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.refresh_aircraft_milestones_after_hours_change()','refresh_aircraft_milestones_after_hours_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.refresh_future_supervision_assignments()','refresh_future_supervision_assignments','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.refresh_learning_program_completion(p_program_id uuid, p_user_id uuid)','refresh_learning_program_completion','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.refresh_maintenance_milestone_statuses()','refresh_maintenance_milestone_statuses','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.refresh_role_based_supervision_requirements()','refresh_role_based_supervision_requirements','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.release_aircraft_auto_grounding(p_aircraft_id uuid, p_defect_id uuid)','release_aircraft_auto_grounding','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.release_expired_aircraft_auto_groundings()','release_expired_aircraft_auto_groundings','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.release_trial_voucher_when_booking_cancelled()','release_trial_voucher_when_booking_cancelled','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.release_xero_token_refresh(p_lock_id uuid)','release_xero_token_refresh','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.rename_aircraft_endorsement_requirement(old_value text, new_value text)','rename_aircraft_endorsement_requirement','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.rename_aircraft_licence_requirement(old_value text, new_value text)','rename_aircraft_licence_requirement','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.revoke_integration_api_key(p_key_id uuid)','revoke_integration_api_key','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.rollback_student_record_import(p_batch_id uuid)','rollback_student_record_import','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.rotate_kiosk_access_token_internal(p_token_prefix text, p_token_hash text, p_token_ciphertext text, p_actor_user_id uuid)','rotate_kiosk_access_token_internal','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.save_instructor_compliance_template(p_course_id uuid, p_name text, p_description text, p_version text, p_source_documents jsonb, p_check_type text, p_is_active boolean, p_items jsonb)','save_instructor_compliance_template','staff_aal2',ARRAY['authenticated','service_role']::text[],false,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.save_membership_products(p_products jsonb)','save_membership_products','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.save_organisation_locations(p_locations jsonb)','save_organisation_locations','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.send_maintenance_due_notifications()','send_maintenance_due_notifications','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.set_booking_location_and_roster()','set_booking_location_and_roster','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.set_integration_webhook_active(p_endpoint_id uuid, p_active boolean)','set_integration_webhook_active','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.set_membership_fee_disposition(p_period_id uuid, p_disposition text, p_reason text)','set_membership_fee_disposition','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.set_organisation_document_acknowledgement(p_document_id uuid, p_acknowledgement_required boolean)','set_organisation_document_acknowledgement','staff_aal2',ARRAY['authenticated','service_role']::text[],true,true,'Staff operation; the function must enforce role and AAL2 internally.'),
  ('public.sign_course_declaration_with_token(p_token text, p_signature_name text, p_member_number text, p_guardian_relationship text, p_guardian_email text, p_guardian_phone text, p_user_agent text)','sign_course_declaration_with_token','anonymous_token_public',ARRAY['anon','authenticated','service_role']::text[],true,true,'Login-free workflow protected by an expiring, scoped token.'),
  ('public.staff_session_has_required_assurance()','staff_session_has_required_assurance','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.student_record_import_fingerprint(p_student_id uuid, p_record_type text, p_row jsonb)','student_record_import_fingerprint','service_worker',ARRAY['service_role']::text[],false,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.submit_learning_quiz(p_step_id uuid, p_answers jsonb)','submit_learning_quiz','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.submit_membership_application(p_membership_class_code text, p_residential_address text, p_service_address text, p_date_of_birth date, p_guardian_name text, p_guardian_consent boolean, p_supports_club_purposes boolean, p_agrees_to_constitution boolean, p_agrees_to_member_guarantee boolean, p_agrees_to_code_of_conduct boolean, p_agrees_to_members_manual boolean, p_privacy_notice_accepted boolean, p_privacy_notice_version text, p_acknowledged_document_ids uuid[], p_applicant_name text, p_phone text, p_update_profile boolean)','submit_membership_application','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.supervisor_available_for_slot(p_supervisor_id uuid, p_start timestamp with time zone, p_end timestamp with time zone, p_exclude_booking_id uuid)','supervisor_available_for_slot','authenticated_self_service',ARRAY['authenticated','service_role']::text[],true,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.supervisor_roster_locations_for_slot(p_supervisor_id uuid, p_start_time timestamp with time zone, p_end_time timestamp with time zone)','supervisor_roster_locations_for_slot','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.sync_duty_segments(p_duty_period_id uuid)','sync_duty_segments','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.sync_duty_segments_after_flight_log_change()','sync_duty_segments_after_flight_log_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.sync_duty_segments_after_period_change()','sync_duty_segments_after_period_change','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.sync_instructor_absence_identity_columns()','sync_instructor_absence_identity_columns','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.sync_linked_learning_enrolments_for_course()','sync_linked_learning_enrolments_for_course','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.sync_linked_learning_enrolments_for_link()','sync_linked_learning_enrolments_for_link','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.sync_member_flight_review_from_endorsements(target_user_id uuid)','sync_member_flight_review_from_endorsements','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.sync_member_role_from_endorsements(target_user_id uuid)','sync_member_role_from_endorsements','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.sync_member_role_from_licences(target_user_id uuid)','sync_member_role_from_licences','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.sync_public_user_email_from_auth()','sync_public_user_email_from_auth','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.sync_trial_voucher_booking_link()','sync_trial_voucher_booking_link','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.sync_user_primary_role()','sync_user_primary_role','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.touch_calendar_integration_updated_at()','touch_calendar_integration_updated_at','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.training_record_audit_entry(p_action text, p_changes jsonb)','training_record_audit_entry','authenticated_self_service',ARRAY['authenticated','service_role']::text[],false,true,'Portal RPC or authenticated support helper with internal ownership/role checks.'),
  ('public.trial_voucher_instructor_available_for_slot(p_instructor_id uuid, p_start_time timestamp with time zone, p_end_time timestamp with time zone)','trial_voucher_instructor_available_for_slot','service_worker',ARRAY['service_role']::text[],true,true,'Background, privileged or internal helper not exposed to browser roles.'),
  ('public.validate_duty_break_change()','validate_duty_break_change','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.validate_duty_period_change()','validate_duty_period_change','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.validate_flight_review_completion()','validate_flight_review_completion','trigger_internal',ARRAY[]::text[],false,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.validate_membership_application_privacy()','validate_membership_application_privacy','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.'),
  ('public.validate_supervisor_roster_locations()','validate_supervisor_roster_locations','trigger_internal',ARRAY[]::text[],true,true,'Invoked only by a database trigger; client EXECUTE is unnecessary.');

alter default privileges for role postgres in schema public revoke execute on functions from public,anon,authenticated,service_role;

do $permissions$
declare f record;m private.function_permission_manifest%rowtype;live_count integer;
begin
 select count(*) into live_count from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public';
 if live_count<>(select count(*) from private.function_permission_manifest) then raise exception 'Function permission manifest count mismatch: % live, % manifested',live_count,(select count(*) from private.function_permission_manifest);end if;
 for f in select format('%I.%I(%s)',n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) signature,p.prosecdef,coalesce(array_to_string(p.proconfig,','),'') like '%search_path=%' fixed_search_path from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'
 loop
  select * into m from private.function_permission_manifest where signature=f.signature;
  if not found then raise exception 'Unmanifested public function: %',f.signature;end if;
  if m.security_definer<>f.prosecdef or m.fixed_search_path<>f.fixed_search_path then raise exception 'Function security metadata drift: %',f.signature;end if;
  execute format('revoke all privileges on function %s from public,anon,authenticated,service_role',f.signature);
  if 'anon'=any(m.allowed_roles) then execute format('grant execute on function %s to anon',f.signature);end if;
  if 'authenticated'=any(m.allowed_roles) then execute format('grant execute on function %s to authenticated',f.signature);end if;
  if 'service_role'=any(m.allowed_roles) then execute format('grant execute on function %s to service_role',f.signature);end if;
 end loop;
end
$permissions$;

revoke all on table private.function_permission_manifest from public,anon,authenticated,service_role;
comment on table private.function_permission_manifest is 'Versioned source of truth for public-schema function execution privileges.';

create or replace function private.assert_function_permission_manifest() returns void language plpgsql security definer set search_path=pg_catalog,private as $assert$
declare missing text;unexpected text;
begin
 select string_agg(l.signature,', ' order by l.signature) into missing from(select format('%I.%I(%s)',n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public')l left join private.function_permission_manifest m using(signature) where m.signature is null;
 select string_agg(m.signature,', ' order by m.signature) into unexpected from private.function_permission_manifest m left join(select format('%I.%I(%s)',n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public')l using(signature) where l.signature is null;
 if missing is not null or unexpected is not null then raise exception 'Function permission manifest drift. Missing: %. Unexpected: %.',coalesce(missing,'none'),coalesce(unexpected,'none');end if;
end
$assert$;
revoke all on function private.assert_function_permission_manifest() from public,anon,authenticated,service_role;

